version: '3.8'

services:
  spring-boot-app:
    image: openjdk:17-jdk-slim
    container_name: ${APPLICATION_NAME}
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - src/main/resources/env/ <your env here>
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_CONNECTING_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

# we can separate database creation with this service creation (suggested)
#    depends_on:
#      - mysql
#
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    env_file:
#      - src/main/resources/env/ <your env here>
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${DATABASE_NAME}
#      MYSQL_USER: ${DATABASE_USERNAME}
#      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - schemas/schemas:/docker-entrypoint-initdb.d
#
#volumes:
#  mysql_data:
