server:
  port: ${SERVER_PORT}

spring:
  profile:
    active: prod
  config:
    import: optional:./env/production.env[.properties]
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: ${DATABASE_CONNECTING_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}